import { ArrowRight } from "lucide-react";

import { SEO } from "@/components/SEO";
import { Button, Eyebrow, ProofBoundary, StatusChip } from "@/components/blueprint";
import { EditorialCtaBand, EditorialSectionIntro, MonochromeMedia } from "@/components/site/editorial";
import { TileGrid } from "@/components/site/TileGrid";
import { breadcrumbJsonLd, webPageJsonLd } from "@/lib/seoStructuredData";

const operatorNeeds = [
  ["Turn a task into a testable decision", "Describe the workflow, conditions, thresholds, unacceptable failures, false-safe consequence, timing, and access constraints."],
  ["See what evidence is missing", "Blueprint separates what the current capture can support from claims that need stronger or physical evidence."],
  ["Evaluate submitted candidates", "When robot or policy candidates exist, they enter the same request and per-claim evidence model."],
  ["Receive a bounded answer", "The result can be positive, negative, partial, or an explicit abstention with the next cheapest experiment."],
] as const;

export default function ForSiteOperators() {
  return (
    <>
      <SEO title="Task Evaluation Runs for site operators | Blueprint" description="Turn a real site-task into a maintained testbed and a bounded decision, with missing evidence and physical requirements made explicit." canonical="/for-site-operators" jsonLd={[webPageJsonLd({ path: "/for-site-operators", name: "Task Evaluation Runs for site operators", description: "The same Task Evaluation Run used by robot teams, explained for site operators." }), breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "For site operators", path: "/for-site-operators" }])]} />
      <section className="bg-canvas"><div className="mx-auto grid max-w-[88rem] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:px-10 lg:py-24"><div><Eyebrow tone="brass" rule>Task Evaluation Run · site-operator use case</Eyebrow><h1 className="mt-5 font-display text-[clamp(2.7rem,5vw,4.8rem)] font-medium leading-[1.01] tracking-[-0.05em] text-ink-900">Turn one real task into a decision you can inspect.</h1><p className="mt-5 max-w-2xl text-[1.05rem] leading-7 text-ink-500">Blueprint captures and maintains the site-task substrate, identifies the evidence each claim needs, evaluates submitted candidates when available, and returns a bounded decision or an explicit abstention.</p><div className="mt-8"><Button asChild variant="brass" size="lg"><a href="/contact/site-operator?interest=task-evaluation-run&requestedOutputs=Task%20Evaluation%20Run&source=for-site-operators">Request a Task Evaluation Run <ArrowRight className="h-4 w-4" /></a></Button></div></div><MonochromeMedia src="/redesign/pov/loading-dock.jpg" alt="Real loading dock used to define a site-task" loading="eager" radius="lg" overlay="soft" className="aspect-[16/11] border border-line"><span className="absolute left-3 top-3"><StatusChip tone="ink" square dot={false}>Illustrative workflow</StatusChip></span></MonochromeMedia></div></section>
      <section className="border-y border-line bg-paper"><div className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><EditorialSectionIntro eyebrow="Same service · same result model" title="Site operators do not need to design an evaluation stack." description="The intake asks for the task, decision, thresholds, consequences, evidence, budget, deadline, rights, and whether physical testing is possible." /><TileGrid cols={4} className="mt-10">{operatorNeeds.map(([title, body]) => <article key={title} className="bg-white p-6"><h2 className="text-title-m font-semibold text-ink-900">{title}</h2><p className="mt-3 text-sm leading-7 text-ink-500">{body}</p></article>)}</TileGrid></div></section>
      <section className="bg-canvas"><div className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><EditorialSectionIntro eyebrow="Maintained learning loop" title="Real site-task → testbed → run → decision or abstention." description="Targeted physical evidence joins the exact decision and testbed identifiers. A user-entered note alone cannot recalibrate an evidence method." /><div className="mt-10 grid gap-5 lg:grid-cols-2"><ProofBoundary level="info" title="Router in plain language">Blueprint uses the least expensive evidence that is trustworthy enough for each question, and asks for stronger evidence only when needed.</ProofBoundary><ProofBoundary level="warn" title="Operator and safety control">Capture windows, privacy, restricted areas, evidence use, physical access, and safety approval remain explicitly controlled. Virtual evidence is never presented as a physical guarantee.</ProofBoundary></div></div></section>
      <section className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><EditorialCtaBand eyebrow="Start with the task" title="Request the same Task Evaluation Run." description="Describe the real workflow and the decision it should inform. Candidates are optional at intake and can be linked when available." imageSrc="/redesign/pov/cold-storage.jpg" imageAlt="Cold-storage site task environment" primaryHref="/contact/site-operator?interest=task-evaluation-run&requestedOutputs=Task%20Evaluation%20Run&source=for-site-operators-cta" primaryLabel="Request a Task Evaluation Run" secondaryHref="/governance" secondaryLabel="Review rights and privacy" dark={false} /></section>
    </>
  );
}
