import { ArrowRight } from "lucide-react";

import { SEO } from "@/components/SEO";
import { Button, Eyebrow, ProofBoundary, StatusChip } from "@/components/blueprint";
import { EditorialCtaBand, EditorialSectionIntro, MonochromeMedia, ProofChip } from "@/components/site/editorial";
import { TileGrid } from "@/components/site/TileGrid";
import { blueprintPositioning, rankingOutcomeCategories } from "@/data/robotPolicyEvaluationClaims";
import { webPageJsonLd } from "@/lib/seoStructuredData";

const lifecycle = [
  ["Real site-task", "Capture the task, conditions, rights, thresholds, and provenance that define the decision."],
  ["Maintained testbed", "Keep an exact versioned substrate behind this run and future decisions."],
  ["Task Evaluation Run", "Submit the decision, claims, consequences, candidates when applicable, evidence, budget, and deadline."],
  ["Cheapest qualified evidence", "Pipeline selects trustworthy-enough methods claim by claim and escalates only when needed."],
  ["Decision or abstention", "Receive the supported answer, unknowns, claim ceiling, and next cheapest experiment."],
  ["Physical learning loop", "Join authoritative physical outcomes to exact identifiers when virtual evidence cannot support the claim."],
] as const;

export default function Home() {
  return <>
    <SEO title="Blueprint | Task Evaluation Runs for real site-tasks" description="Blueprint turns a real site-task into a maintained testbed and returns a bounded decision or explicit abstention using the least expensive qualified evidence." canonical="/" jsonLd={[webPageJsonLd({ path: "/", name: "Blueprint Task Evaluation Runs", description: blueprintPositioning })]} />
    <section className="bg-canvas"><div className="mx-auto grid max-w-[88rem] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:px-10 lg:py-24"><div><Eyebrow tone="brass" rule>Real-site Task Evaluation Runs</Eyebrow><h1 className="mt-5 font-display text-[clamp(2.9rem,5.7vw,5.4rem)] font-medium leading-[0.98] tracking-[-0.055em] text-ink-900">Turn a real site-task into a decision you can defend.</h1><p className="mt-5 max-w-2xl text-[1.08rem] leading-8 text-ink-500">{blueprintPositioning}</p><div className="mt-8"><Button asChild variant="brass" size="lg"><a href="/contact/robot-team?interest=task-evaluation-run&requestedOutputs=Task%20Evaluation%20Run&source=home">Request a Task Evaluation Run <ArrowRight className="h-4 w-4" /></a></Button></div><div className="mt-6 flex flex-wrap gap-2"><ProofChip>Decision, not backend selection</ProofChip><ProofChip>Explicit abstention supported</ProofChip><ProofChip>Physical evidence when required</ProofChip></div></div><MonochromeMedia src="/redesign/pov/packing-cell.jpg" alt="Real packing-cell task environment" loading="eager" radius="lg" overlay="soft" className="aspect-[16/11] border border-line"><span className="absolute left-3 top-3"><StatusChip tone="ink" square dot={false}>Real-site substrate</StatusChip></span></MonochromeMedia></div></section>
    <section className="border-y border-line bg-paper"><div className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><EditorialSectionIntro eyebrow="One product" title="One lifecycle from task to maintained evidence." description="Robot teams and site operators enter through different explanations, then use the same service, intake, workflow, result contract, and call to action." /><ol className="mt-10 grid gap-px overflow-hidden border border-line bg-line md:grid-cols-3 lg:grid-cols-6">{lifecycle.map(([title, body], index) => <li key={title} className="bg-white p-5"><span className="font-mono text-xs text-brass">0{index + 1}</span><h2 className="mt-3 font-semibold text-ink-900">{title}</h2><p className="mt-2 text-sm leading-6 text-ink-500">{body}</p></li>)}</ol></div></section>
    <section className="bg-canvas"><div className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><EditorialSectionIntro eyebrow="Truthful outcomes" title="A useful run does not have to name a winner." description="The result is a set of per-claim conclusions and limits, never one undifferentiated score." /><TileGrid cols={5} className="mt-10">{rankingOutcomeCategories.map((item) => <article key={item.label} className="bg-white p-5"><h2 className="font-semibold text-ink-900">{item.label}</h2><p className="mt-3 text-sm leading-6 text-ink-500">{item.body}</p></article>)}</TileGrid><div className="mt-8"><ProofBoundary level="info" title="Illustrative abstention—not a ranking claim">Candidate reachability may be supported while onsite outperformance remains unresolved. In that case Blueprint shows a partial decision or abstention, the validation envelope, and the next evidence needed. It does not infer a winner from raw scores.</ProofBoundary></div></div></section>
    <section className="border-y border-line bg-paper"><div className="mx-auto grid max-w-[88rem] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:px-10 lg:py-24"><div><Eyebrow tone="brass" rule>For robot teams</Eyebrow><h2 className="mt-4 text-title-l font-semibold text-ink-900">Compare internal candidates and decide whether field time is justified.</h2><p className="mt-3 text-sm leading-7 text-ink-500">Bring policies or checkpoints when applicable. Discover compatibility failures, unresolved claims, and the evidence that would change the decision.</p><Button asChild variant="secondary" className="mt-6"><a href="/for-robot-teams">Robot-team use case <ArrowRight className="h-4 w-4" /></a></Button></div><div><Eyebrow tone="brass" rule>For site operators</Eyebrow><h2 className="mt-4 text-title-l font-semibold text-ink-900">Turn the task into a testable decision before candidates are even available.</h2><p className="mt-3 text-sm leading-7 text-ink-500">See what evidence is missing, evaluate submissions when available, and retain control over rights, privacy, access, and physical testing.</p><Button asChild variant="secondary" className="mt-6"><a href="/for-site-operators">Site-operator use case <ArrowRight className="h-4 w-4" /></a></Button></div></div></section>
    <section className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><EditorialCtaBand eyebrow="Start with the decision" title="Request a Task Evaluation Run." description="Describe the site-task, decision, thresholds, consequences, evidence, budget, deadline, and restrictions. Blueprint owns the evidence-routing complexity." imageSrc="/redesign/pov/route-scan.jpg" imageAlt="Captured real-site route" primaryHref="/contact/robot-team?interest=task-evaluation-run&requestedOutputs=Task%20Evaluation%20Run&source=home-cta" primaryLabel="Request a Task Evaluation Run" secondaryHref="/how-it-works" secondaryLabel="How it works" /></section>
  </>;
}
