import { SEO } from "@/components/SEO";
import { Eyebrow, ProofBoundary } from "@/components/blueprint";
import { EditorialCtaBand, EditorialSectionIntro } from "@/components/site/editorial";
import { TileGrid } from "@/components/site/TileGrid";
import { breadcrumbJsonLd, webPageJsonLd } from "@/lib/seoStructuredData";

const steps = [
  ["1", "Describe the site-task and decision", "State the question, claims, thresholds and units, false-safe consequence, acceptable risk, budget, deadline, available evidence, rights, and physical-testing constraints."],
  ["2", "Link the maintained testbed", "The request names an exact Site-Task Testbed ID, version, and digest. Raw capture provenance remains authoritative; derived evidence does not silently upgrade the claim."],
  ["3", "Plan the cheapest qualified evidence", "Pipeline qualifies and selects geometry, real observations, traditional simulation, world models, provider tools, or physical evidence claim by claim. WebApp does not select the backend."],
  ["4", "Measure and aggregate", "Each method reports what it measured, its qualification profile, validation envelope, uncertainty, disagreement, coverage, and exact artifacts."],
  ["5", "Return a decision or abstention", "The result may be positive, negative, partial, blocked, or abstained. Unknown states fail closed and an abstention can never be converted into a winner from raw scores."],
  ["6", "Run the next cheapest experiment", "When evidence is insufficient, Blueprint identifies the least expensive stronger test and whether authoritative physical evidence is necessary."],
] as const;

export default function HowItWorks() {
  return <><SEO title="How a Task Evaluation Run works | Blueprint" description="From real site-task to maintained testbed, qualified evidence plan, bounded decision or abstention, and physical learning loop." canonical="/how-it-works" jsonLd={[webPageJsonLd({ path: "/how-it-works", name: "How a Task Evaluation Run works", description: "The Blueprint Task Evaluation Run lifecycle." }), breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "How it works", path: "/how-it-works" }])]} /><section className="bg-canvas"><div className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><Eyebrow tone="brass" rule>How it works</Eyebrow><h1 className="mt-5 max-w-4xl font-display text-[clamp(2.7rem,5vw,4.8rem)] font-medium leading-[1.01] tracking-[-0.05em] text-ink-900">How a Task Evaluation Run works.</h1><p className="mt-5 max-w-3xl text-[1.05rem] leading-8 text-ink-500">One real site-task becomes a maintained testbed. One decision request becomes a qualified evidence plan. The result is a bounded answer or an explicit abstention—not a backend choice or guaranteed ranking.</p></div></section><section className="border-y border-line bg-paper"><div className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><EditorialSectionIntro eyebrow="Six stages" title="From real task to inspectable decision." description="Pipeline owns method qualification, routing, normalized evidence, and scientific verdicts. WebApp owns secure intake, authorization, durable state, projection, and access." /><TileGrid cols={3} className="mt-10">{steps.map(([number, title, body]) => <article key={number} className="bg-white p-6"><span className="font-mono text-sm text-brass">{number}</span><h2 className="mt-3 text-title-m font-semibold text-ink-900">{title}</h2><p className="mt-3 text-sm leading-7 text-ink-500">{body}</p></article>)}</TileGrid><div className="mt-8 grid gap-5 lg:grid-cols-2"><ProofBoundary level="info" title="Router in plain language">Blueprint uses the least expensive evidence that is trustworthy enough for each question, and asks for stronger evidence only when needed.</ProofBoundary><ProofBoundary level="warn" title="Claim ceiling">Simulation, generated evidence, provider availability, and export eligibility are not physical guarantees. Safety approval remains external.</ProofBoundary></div></div></section><section className="mx-auto max-w-[88rem] px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><EditorialCtaBand eyebrow="One intake" title="Request a Task Evaluation Run." description="Robot teams and site operators use the same decision contract and result model." imageSrc="/redesign/pov/inspection-bench.jpg" imageAlt="Real-site inspection task" primaryHref="/contact/robot-team?interest=task-evaluation-run&requestedOutputs=Task%20Evaluation%20Run&source=how-it-works" primaryLabel="Request a Task Evaluation Run" secondaryHref="/pricing" secondaryLabel="See pricing" /></section></>;
}
