import { spawnSync } from "node:child_process";
import crypto from "node:crypto";

const baseUrl = String(process.env.ALPHA_BASE_URL || process.env.BASE_URL || "").trim().replace(/\/+$/, "");
const bearerToken = String(process.env.ALPHA_BEARER_TOKEN || "").trim();

if (!baseUrl) {
  console.error("ALPHA_BASE_URL or BASE_URL is required.");
  process.exit(1);
}

async function fetchJson(url, init) {
  const response = await fetch(url, init);
  const text = await response.text();
  let json = null;
  try {
    json = text ? JSON.parse(text) : null;
  } catch {
    json = null;
  }
  return { response, json, text };
}

async function getCsrfSession() {
  const { response, json } = await fetchJson(`${baseUrl}/api/csrf`);
  if (!response.ok || !json?.csrfToken) {
    throw new Error("Failed to fetch CSRF token.");
  }
  const cookie = response.headers.get("set-cookie");
  if (!cookie) {
    throw new Error("CSRF cookie was not returned.");
  }
  return {
    csrfToken: json.csrfToken,
    cookie: cookie.split(";")[0],
  };
}

async function runHealthChecks() {
  const health = await fetchJson(`${baseUrl}/health`);
  if (!health.response.ok) {
    throw new Error(`/health failed with ${health.response.status}`);
  }

  const ready = await fetchJson(`${baseUrl}/health/ready`);
  if (!ready.response.ok) {
    throw new Error(`/health/ready failed with ${ready.response.status}: ${ready.text}`);
  }

  console.log("Health checks passed.");
}

function runAgentRuntimeSmoke() {
  const result = spawnSync("npm", ["run", "smoke:agent"], {
    cwd: process.cwd(),
    stdio: "inherit",
    env: process.env,
  });

  if (result.status !== 0) {
    throw new Error("Agent runtime smoke test failed.");
  }
}

async function runInboundSmoke(csrfSession) {
  const payload = {
    requestId: `alpha-smoke-${crypto.randomUUID()}`,
    firstName: process.env.ALPHA_SMOKE_FIRST_NAME || "Alpha",
    lastName: process.env.ALPHA_SMOKE_LAST_NAME || "Smoke",
    company: process.env.ALPHA_SMOKE_COMPANY || "Blueprint Alpha Smoke",
    roleTitle: process.env.ALPHA_SMOKE_ROLE || "Launch Ops",
    email: process.env.ALPHA_SMOKE_EMAIL || "alpha-smoke@example.com",
    budgetBucket: process.env.ALPHA_SMOKE_BUDGET_BUCKET || "$50K-$300K",
    requestedLanes: ["qualification"],
    helpWith: [],
    buyerType: "site_operator",
    siteName: process.env.ALPHA_SMOKE_SITE_NAME || "Alpha Smoke Site",
    siteLocation: process.env.ALPHA_SMOKE_SITE_LOCATION || "Durham, NC",
    taskStatement: process.env.ALPHA_SMOKE_TASK || "Validate alpha launch qualification automation.",
    details: "Launch smoke submission generated by scripts/launch-smoke.mjs",
    context: {
      sourcePageUrl: `${baseUrl}/launch-smoke`,
      utm: {},
    },
  };

  const { response, json, text } = await fetchJson(`${baseUrl}/api/inbound-request`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-csrf-token": csrfSession.csrfToken,
      cookie: csrfSession.cookie,
    },
    body: JSON.stringify(payload),
  });

  if (response.status !== 201 || !json?.ok) {
    throw new Error(`Inbound smoke failed: ${response.status} ${text}`);
  }

  console.log(`Inbound smoke passed (${json.requestId}).`);
}

async function runPostSignupSmoke(csrfSession) {
  if (!bearerToken) {
    console.log("Skipping post-signup smoke because ALPHA_BEARER_TOKEN is not set.");
    return;
  }

  const payload = {
    blueprintId: process.env.ALPHA_SMOKE_BLUEPRINT_ID || "alpha-smoke-blueprint",
    userId: process.env.ALPHA_SMOKE_USER_ID || "alpha-smoke-user",
    companyName: process.env.ALPHA_SMOKE_COMPANY || "Blueprint Alpha Smoke",
    address: process.env.ALPHA_SMOKE_ADDRESS || "101 Launch Way, Durham, NC",
    companyUrl: process.env.ALPHA_SMOKE_COMPANY_URL || "https://example.com/alpha-smoke",
    contactName: `${process.env.ALPHA_SMOKE_FIRST_NAME || "Alpha"} ${process.env.ALPHA_SMOKE_LAST_NAME || "Smoke"}`,
    contactEmail: process.env.ALPHA_SMOKE_EMAIL || "alpha-smoke@example.com",
    contactPhone: process.env.ALPHA_SMOKE_PHONE || "555-010-2026",
    mappingDate: process.env.ALPHA_SMOKE_MAPPING_DATE || "2026-03-23",
    mappingTime: process.env.ALPHA_SMOKE_MAPPING_TIME || "10:00",
  };

  const { response, json, text } = await fetchJson(`${baseUrl}/api/post-signup-workflows`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${bearerToken}`,
      "x-csrf-token": csrfSession.csrfToken,
      cookie: csrfSession.cookie,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok || json?.success !== true) {
    throw new Error(`Post-signup smoke failed: ${response.status} ${text}`);
  }

  console.log(`Post-signup smoke passed (${json.blueprintId}).`);
}

try {
  await runHealthChecks();
  runAgentRuntimeSmoke();
  const csrfSession = await getCsrfSession();
  await runInboundSmoke(csrfSession);
  await runPostSignupSmoke(csrfSession);
  console.log("Launch smoke passed.");
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
