import { z } from "zod";

const derivedAssetEntrySchema = z.object({
  status: z.string().min(1),
  manifest_uri: z.string().optional(),
  artifact_uri: z.string().optional(),
  updated_at: z.union([z.string(), z.null()]).optional(),
}).passthrough();

const buyerTrustScoreSchema = z.object({
  score: z.number(),
  band: z.enum(["high", "medium", "low"]),
  reasons: z.array(z.string()).default([]),
});

const providerRunSummarySchema = z.object({
  provider_name: z.string().optional(),
  provider_model: z.string().optional(),
  provider_run_id: z.string().optional(),
  status: z.string().optional(),
  preview_manifest_uri: z.string().optional(),
  cost_usd: z.number().nullable().optional(),
  latency_ms: z.number().nullable().optional(),
  failure_reason: z.string().nullable().optional(),
  provenance: z.record(z.unknown()).nullable().optional(),
}).passthrough();

const robotEvalDatasetCardArtifactUrisSchema = z.object({
  post_training_data_package_uri: z.string().nullable().optional(),
  delivery_manifest_uri: z.string().nullable().optional(),
  manifest_uri: z.string().nullable().optional(),
  legacy_manifest_uri: z.string().nullable().optional(),
  site_card_uri: z.string().nullable().optional(),
  task_cards_uri: z.string().nullable().optional(),
  scenario_cards_uri: z.string().nullable().optional(),
  eval_cards_uri: z.string().nullable().optional(),
  annotation_backlog_uri: z.string().nullable().optional(),
  proof_boundaries_uri: z.string().nullable().optional(),
  rights_packet_uri: z.string().nullable().optional(),
  rights_ledger_uri: z.string().nullable().optional(),
  task_ontology_v1_uri: z.string().nullable().optional(),
  task_library_uri: z.string().nullable().optional(),
  scenario_family_library_uri: z.string().nullable().optional(),
  scenario_library_uri: z.string().nullable().optional(),
  scoring_methodology_uri: z.string().nullable().optional(),
  task_thresholds_uri: z.string().nullable().optional(),
  publication_readiness_uri: z.string().nullable().optional(),
  scene_asset_inventory_uri: z.string().nullable().optional(),
  scene_asset_dependency_audit_uri: z.string().nullable().optional(),
  scene_asset_preflight_uri: z.string().nullable().optional(),
  scene_asset_inspection_uri: z.string().nullable().optional(),
  scene_frame_estimate_uri: z.string().nullable().optional(),
  collider_proxy_plan_uri: z.string().nullable().optional(),
  cpu_scene_proxy_manifest_uri: z.string().nullable().optional(),
  cpu_preflight_scorecard_uri: z.string().nullable().optional(),
  task_anchor_proposal_manifest_uri: z.string().nullable().optional(),
  episode_spec_manifest_uri: z.string().nullable().optional(),
  episode_specs_uri: z.string().nullable().optional(),
  spawn_pose_validation_manifest_uri: z.string().nullable().optional(),
  cpu_preflight_manifest_uri: z.string().nullable().optional(),
  pre_gpu_readiness_summary_uri: z.string().nullable().optional(),
  cpu_simulator_preflight_manifest_uri: z.string().nullable().optional(),
  gpu_handoff_packet_uri: z.string().nullable().optional(),
  gpu_owner_system_proof_schema_uri: z.string().nullable().optional(),
  gpu_run_checklist_uri: z.string().nullable().optional(),
  owner_gpu_simulator_execution_blocked_manifest_uri: z.string().nullable().optional(),
  recorded_trace_eval_report_uri: z.string().nullable().optional(),
  policy_eval_report_uri: z.string().nullable().optional(),
  robot_team_test_submission_modalities_uri: z.string().nullable().optional(),
  prediction_outcome_ledger_uri: z.string().nullable().optional(),
  prediction_vs_actual_summary_uri: z.string().nullable().optional(),
}).passthrough();

const robotEvalDatasetSummarySchema = z.object({
  dataset_state: z.string().nullable().optional(),
  dataset_statuses: z.array(z.string()).optional(),
  ready_to_evaluate_publishable: z.boolean().nullable().optional(),
  publication_label: z.string().nullable().optional(),
  required_artifact_status: z.string().nullable().optional(),
  missing_required_artifacts: z.array(z.string()).optional(),
  missing_proof_labels: z.array(z.string()).optional(),
  task_count: z.number().nullable().optional(),
  scenario_count: z.number().nullable().optional(),
  site_card_count: z.number().nullable().optional(),
  task_card_count: z.number().nullable().optional(),
  scenario_card_count: z.number().nullable().optional(),
  eval_card_count: z.number().nullable().optional(),
  annotation_backlog_count: z.number().nullable().optional(),
  prediction_record_count: z.number().nullable().optional(),
  manifest_uri: z.string().nullable().optional(),
  card_artifact_uris: robotEvalDatasetCardArtifactUrisSchema.nullable().optional(),
  claim_boundary: z.record(z.unknown()).nullable().optional(),
}).passthrough();

const robotEvalJobSummarySchema = z.object({
  status: z.string().nullable().optional(),
  job_request_uri: z.string().nullable().optional(),
  scheduler_decision_uri: z.string().nullable().optional(),
  worker_launch_plan_uri: z.string().nullable().optional(),
  worker_manifest_uri: z.string().nullable().optional(),
  gpu_provider_launch_request_uri: z.string().nullable().optional(),
  gpu_provider_launcher_result_uri: z.string().nullable().optional(),
  runpod_provider_adapter_result_uri: z.string().nullable().optional(),
  gpu_cost_control_ledger_uri: z.string().nullable().optional(),
  startup_architecture_audit_uri: z.string().nullable().optional(),
  worker_runtime_manifest_uri: z.string().nullable().optional(),
  worker_runtime_preflight_uri: z.string().nullable().optional(),
  job_run_manifest_uri: z.string().nullable().optional(),
  proof_boundary_uri: z.string().nullable().optional(),
  blocked_manifest_uri: z.string().nullable().optional(),
  simulator_execution_proven: z.boolean().nullable().optional(),
  rank_fidelity_result_proven: z.boolean().nullable().optional(),
  public_claim_upgrade_allowed: z.boolean().nullable().optional(),
}).passthrough();

const robotEvalPreflightSummarySchema = z.object({
  status: z.string().nullable().optional(),
  scene_asset_preflight_status: z.string().nullable().optional(),
  episode_spec_status: z.string().nullable().optional(),
  episode_count: z.number().nullable().optional(),
  cpu_simulator_preflight_status: z.string().nullable().optional(),
  local_cpu_preflight_smoke_ran: z.boolean().nullable().optional(),
  ready_for_owner_gpu_preflight: z.boolean().nullable().optional(),
  owner_gpu_simulator_execution_proven: z.boolean().nullable().optional(),
  dependency_warning_count: z.number().nullable().optional(),
  missing_dependency_count: z.number().nullable().optional(),
  remote_ref_count: z.number().nullable().optional(),
  real_collider_proven: z.boolean().nullable().optional(),
  proxy_estimated: z.boolean().nullable().optional(),
  missing_collider: z.boolean().nullable().optional(),
  review_required: z.boolean().nullable().optional(),
  collider_backend_labels: z.array(z.string()).optional(),
  collider_backend_blockers: z.array(z.string()).optional(),
  install_instructions: z.array(z.string()).optional(),
  scene_asset_inventory_uri: z.string().nullable().optional(),
  scene_asset_dependency_audit_uri: z.string().nullable().optional(),
  scene_asset_preflight_uri: z.string().nullable().optional(),
  scene_asset_inspection_uri: z.string().nullable().optional(),
  scene_frame_estimate_uri: z.string().nullable().optional(),
  collider_proxy_plan_uri: z.string().nullable().optional(),
  cpu_scene_proxy_manifest_uri: z.string().nullable().optional(),
  cpu_preflight_scorecard_uri: z.string().nullable().optional(),
  task_anchor_proposal_manifest_uri: z.string().nullable().optional(),
  episode_spec_manifest_uri: z.string().nullable().optional(),
  episode_specs_uri: z.string().nullable().optional(),
  spawn_pose_validation_manifest_uri: z.string().nullable().optional(),
  cpu_preflight_manifest_uri: z.string().nullable().optional(),
  pre_gpu_readiness_summary_uri: z.string().nullable().optional(),
  cpu_simulator_preflight_manifest_uri: z.string().nullable().optional(),
  gpu_handoff_packet_uri: z.string().nullable().optional(),
  gpu_owner_system_proof_schema_uri: z.string().nullable().optional(),
  gpu_run_checklist_uri: z.string().nullable().optional(),
  owner_gpu_simulator_execution_blocked_manifest_uri: z.string().nullable().optional(),
  simulator_execution_proven: z.boolean().nullable().optional(),
  rank_fidelity_result_proven: z.boolean().nullable().optional(),
  non_ranking_operational_claim_validated: z.boolean().nullable().optional(),
  public_claim_upgrade_allowed: z.boolean().nullable().optional(),
}).passthrough();

const evaluationReadinessSchema = z.object({
  qualification_state: z.string().optional(),
  opportunity_state: z.string().optional(),
  buyer_trust_score: buyerTrustScoreSchema.optional(),
  qualification_summary: z.record(z.unknown()).nullable().optional(),
  capture_quality_summary: z.record(z.unknown()).nullable().optional(),
  // PIPE-02: rights/privacy verdict the WebApp gates buyer-facing progression on.
  rights_review_status: z.enum(["cleared", "needs_review", "blocked"]).nullable().optional(),
  rights_and_compliance: z.record(z.unknown()).optional(),
  privacy_processing: z.record(z.unknown()).optional(),
  missing_evidence: z.array(z.string()).optional(),
  robot_eval_dataset_summary: robotEvalDatasetSummarySchema.nullable().optional(),
  robot_eval_job_summary: robotEvalJobSummarySchema.nullable().optional(),
  robot_eval_preflight_summary: robotEvalPreflightSummarySchema.nullable().optional(),
  preview_status: z.string().nullable().optional(),
  provider_run: providerRunSummarySchema.nullable().optional(),
}).passthrough();

export const pipelineAttachmentSyncPayloadSchema = z.object({
  schema_version: z.literal("v1"),
  site_submission_id: z.string().optional().default(""),
  request_id: z.string().optional().default(""),
  buyer_request_id: z.string().optional().default(""),
  capture_job_id: z.string().optional().default(""),
  scene_id: z.string().optional().default(""),
  capture_id: z.string().optional().default(""),
  pipeline_prefix: z.string().optional().default(""),
  qualification_state: z.string().optional().default(""),
  opportunity_state: z.string().optional().default(""),
  authoritative_state_update: z.boolean().optional().default(false),
  artifacts: z.record(z.unknown()).optional().default({}),
  derived_assets: z.record(derivedAssetEntrySchema).optional().default({}),
  evaluation_readiness: evaluationReadinessSchema.optional(),
});

export type PipelineAttachmentSyncPayload = z.infer<
  typeof pipelineAttachmentSyncPayloadSchema
>;

export function parsePipelineAttachmentSyncPayload(
  payload: unknown,
): PipelineAttachmentSyncPayload {
  return pipelineAttachmentSyncPayloadSchema.parse(payload);
}
